# Generated by Django 3.1.7 on 2021-04-02 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('teachers', '0001_initial'), ('teachers', '0002_auto_20210330_2128'), ('teachers', '0003_auto_20210330_2129'), ('teachers', '0004_auto_20210330_2142'), ('teachers', '0005_auto_20210330_2149'), ('teachers', '0006_auto_20210331_1408'), ('teachers', '0007_auto_20210331_2029')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('pic_url', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=25, unique=True)),
                ('phoneNum', models.CharField(max_length=14, null=True)),
                ('roomNum', models.CharField(max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='subjectTaughtBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'subject')},
            },
        ),
    ]
