# Generated by Django 3.1.7 on 2021-04-03 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('image_url', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(default='avatar7.png', null=True, upload_to='')),
                ('email', models.CharField(max_length=25, unique=True)),
                ('phoneNum', models.CharField(max_length=14, null=True)),
                ('roomNum', models.CharField(max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectTaughtBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'subject')},
            },
        ),
    ]
