# Generated by Django 3.1.7 on 2021-03-30 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20210330_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='profilePic',
            new_name='pic_url',
        ),
    ]
