# Generated by Django 3.1.7 on 2021-03-30 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_auto_20210330_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='firstName',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='lastName',
            new_name='lastname',
        ),
    ]
