# Generated by Django 3.1.7 on 2021-03-30 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_auto_20210330_2142'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjecttaughtby',
            unique_together={('teacher', 'subject')},
        ),
    ]
