# Generated by Django 3.1.7 on 2021-03-31 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_auto_20210330_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='phoneNum',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='roomNum',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
