# Generated by Django 3.1.7 on 2021-04-01 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importdata', '0003_auto_20210401_0732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zipprofilefile',
            old_name='zipFile',
            new_name='picZipFile',
        ),
    ]
