# Generated by Django 3.1.7 on 2021-04-01 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importdata', '0004_auto_20210401_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersfile',
            name='csvFile',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='zipprofilefile',
            name='picZipFile',
            field=models.FileField(upload_to=''),
        ),
    ]
